
services:
  backend:
    build: .
    container_name: backend_istla
    ports:
      - "6000:6000"
    env_file:
      - .env
    environment:
      - ServerDB=db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./resources:/app/resources
      - ./imagen:/app/imagen
      - ./pdf:/app/pdf
    restart: always

  db:
    image: postgres:15-alpine
    container_name: db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1020"
      POSTGRES_DB: istla
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d istla"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./ddl.sql:/docker-entrypoint-initdb.d/1-ddl.sql
      - ./dml.sql:/docker-entrypoint-initdb.d/2-dml.sql

volumes:
  db_data: